/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gitissues_GitIssues */

#ifndef _Included_gitissues_GitIssues
#define _Included_gitissues_GitIssues
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gitissues_GitIssues
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gitissues_GitIssues_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
