/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.4/samples
 */
plugins {
    kotlin("jvm") version "2.2.0" apply false
}
